spring.application.name=research_output

spring.datasource.url=${jdbc_url_research_output}
spring.datasource.username=${jdbc_username}
spring.datasource.password=${jdbc_password}
spring.datasource.driver-class-name=${jdbc_class_name}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
