 export interface SelectOption {
  value: string;
  label: string;
}

export interface UniversityOption {
  code: string;
  name: string;
}

export const AUTHOR_GENDER_OPTIONS: SelectOption[] = [
  { value: 'FEMALE', label: 'Female' },
  { value: 'MALE', label: 'Male' }
];

export const AUTHOR_POPULATION_GROUP_OPTIONS: SelectOption[] = [
  { value: 'BLACK_AFRICAN', label: 'Black African' },
  { value: 'COLOURED', label: 'Coloured' },
  { value: 'INDIAN_ASIAN', label: 'Indian/Asian' },
  { value: 'WHITE', label: 'White' }
];

export const AUTHOR_SA_RESIDENCY_OPTIONS: SelectOption[] = [
  { value: 'TEMPORARY_RESIDENT', label: 'Temporary Resident' },
  { value: 'PERMANENT_RESIDENT', label: 'Permanent Resident' },
  { value: 'CITIZEN', label: 'Citizen' },
  { value: 'NONE', label: 'None' }
];

export const AUTHOR_EMPLOYMENT_STATUS_OPTIONS: SelectOption[] = [
  { value: 'PERMANENT', label: 'Permanent' },
  { value: 'CONTRACT_TEMPORARY', label: 'Contract / Temporary' },
  { value: 'VISITING_SCHOLAR', label: 'Visiting Scholar' },
  { value: 'STUDENT', label: 'Student' },
  { value: 'RETIRED', label: 'Retired' },
  { value: 'DECEASED', label: 'Deceased' },
  { value: 'OTHER', label: 'Other (Specify)' }
];

export const AUTHOR_ACADEMIC_TITLE_OPTIONS: SelectOption[] = [
  { value: 'ASSOCIATE_PROFESSOR', label: 'Associate Professor' },
  { value: 'BELOW_JUNIOR_LECTURER', label: 'Below Junior Lecturer' },
  { value: 'JUNIOR_LECTURER', label: 'Junior Lecturer' },
  { value: 'LECTURER', label: 'Lecturer' },
  { value: 'POSTDOC', label: 'Postdoc' },
  { value: 'PROFESSOR', label: 'Professor' },
  { value: 'RESEARCH_FELLOW', label: 'Research Fellow' },
  { value: 'SENIOR_LECTURER', label: 'Senior Lecturer' },
  { value: 'STUDENT', label: 'Student' },
  { value: 'OTHER', label: 'Other (Specify)' }
];

export const AUTHOR_HIGHEST_QUALIFICATION_OPTIONS: SelectOption[] = [
  { value: 'UG_DIP_CERT_1_2', label: 'UG Dip/Cert (1 or 2yrs)' },
  { value: 'UG_DIP_CERT_3', label: 'UG Dip/Cert (3yrs)' },
  { value: 'FIRST_BACHELOR_3', label: '1st Bach Deg (3yrs)' },
  { value: 'FIRST_BACHELOR_4_PLUS', label: '1st Bach Deg (4yrs or more)' },
  { value: 'PG_DIP_CERT', label: 'PG/Dip/Post Dip Dip/Cert' },
  { value: 'PG_BACHELOR', label: 'PG Bach Deg' },
  { value: 'HONOURS_NH_DIP', label: 'Honours/NH Dip' },
  { value: 'MASTERS', label: 'Masters/Masters Dip' },
  { value: 'DOCTORATE', label: 'Doctorate' },
  { value: 'OTHER', label: 'Other Qualification (Specify)' }
];

export const SA_HEI_OPTIONS: UniversityOption[] = [
  { code: 'CPUT', name: 'Cape Peninsula University of Technology' },
  { code: 'CUT', name: 'Central University of Technology' },
  { code: 'DUT', name: 'Durban University of Technology' },
  { code: 'MUT', name: 'Mangosuthu University of Technology' },
  { code: 'NMU', name: 'Nelson Mandela University' },
  { code: 'NWU', name: 'North-West University' },
  { code: 'RU', name: 'Rhodes University' },
  { code: 'SMU', name: 'Sefako Makgatho Health Sciences University' },
  { code: 'SPU', name: 'Sol Plaatje University' },
  { code: 'SU', name: 'Stellenbosch University' },
  { code: 'TUT', name: 'Tshwane University of Technology' },
  { code: 'UCT', name: 'University of Cape Town' },
  { code: 'UFH', name: 'University of Fort Hare' },
  { code: 'UJ', name: 'University of Johannesburg' },
  { code: 'UKZN', name: 'University of KwaZulu-Natal' },
  { code: 'UL', name: 'University of Limpopo' },
  { code: 'UMP', name: 'University of Mpumalanga' },
  { code: 'UP', name: 'University of Pretoria' },
  { code: 'UNISA', name: 'University of South Africa' },
  { code: 'UFS', name: 'University of the Free State' },
  { code: 'UWC', name: 'University of the Western Cape' },
  { code: 'WITS', name: 'University of the Witwatersrand' },
  { code: 'UNIVEN', name: 'University of Venda' },
  { code: 'UNIZULU', name: 'University of Zululand' },
  { code: 'VUT', name: 'Vaal University of Technology' },
  { code: 'WSU', name: 'Walter Sisulu University' }
];

export const ISO_3166_COUNTRY_OPTIONS: string[] = [
  'Afghanistan',
  'Aland Islands',
  'Albania',
  'Algeria',
  'American Samoa',
  'Andorra',
  'Angola',
  'Anguilla',
  'Antarctica',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Aruba',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bermuda',
  'Bhutan',
  'Bolivia (Plurinational State of)',
  'Bonaire, Sint Eustatius and Saba',
  'Bosnia and Herzegovina',
  'Botswana',
  'Bouvet Island',
  'Brazil',
  'British Indian Ocean Territory',
  'Brunei Darussalam',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cayman Islands',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo (Democratic Republic of the)',
  'Cook Islands',
  'Costa Rica',
  'Cote d\'Ivoire',
  'Croatia',
  'Cuba',
  'Curacao',
  'Cyprus',
  'Czechia',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Falkland Islands (Malvinas)',
  'Faroe Islands',
  'Fiji',
  'Finland',
  'France',
  'French Guiana',
  'French Polynesia',
  'French Southern Territories',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Gibraltar',
  'Greece',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guam',
  'Guatemala',
  'Guernsey',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Heard Island and McDonald Islands',
  'Holy See',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran (Islamic Republic of)',
  'Iraq',
  'Ireland',
  'Isle of Man',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jersey',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea (Democratic People\'s Republic of)',
  'Korea (Republic of)',
  'Kuwait',
  'Kyrgyzstan',
  'Lao People\'s Democratic Republic',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macao',
  'Macedonia (the former Yugoslav Republic of)',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Martinique',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Mexico',
  'Micronesia (Federated States of)',
  'Moldova (Republic of)',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Montserrat',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Caledonia',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine, State of',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Pitcairn',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Reunion',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'Saint Barthelemy',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin (French part)',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Sint Maarten (Dutch part)',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Georgia and the South Sandwich Islands',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Svalbard and Jan Mayen',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syrian Arab Republic',
  'Taiwan, Province of China',
  'Tajikistan',
  'Tanzania, United Republic of',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tokelau',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Turks and Caicos Islands',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom of Great Britain and Northern Ireland',
  'United States of America',
  'United States Minor Outlying Islands',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Venezuela (Bolivarian Republic of)',
  'Viet Nam',
  'Virgin Islands (British)',
  'Virgin Islands (U.S.)',
  'Wallis and Futuna',
  'Western Sahara',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];
